<?php
require_once __DIR__ . '/db.php';

$error = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $username = $_POST['username'] ?? '';
    $password = $_POST['password'] ?? '';

    $stmt = $pdo->prepare('SELECT id, username, password_hash, role FROM users WHERE username = :u LIMIT 1');
    $stmt->execute(['u' => $username]);
    $user = $stmt->fetch();
    if ($user) {
        $hash = $user['password_hash'];
        $ok = false;
        if (password_verify($password, $hash)) {
            $ok = true;
        } else {
            // fallback to crypt comparison for hashes generated by Postgres crypt()
            if (strlen($hash) > 0 && crypt($password, $hash) === $hash) {
                $ok = true;
            }
        }

        if ($ok) {
            $_SESSION['user'] = [
                'id' => $user['id'],
                'username' => $user['username'],
                'role' => $user['role'],
            ];
            header('Location: dashboard.php');
            exit;
        }
    }
    $error = 'Usuario o contraseña inválidos';
}

?>
<?php
require_once __DIR__ . '/db.php';

$error = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $username = $_POST['username'] ?? '';
    $password = $_POST['password'] ?? '';

    $stmt = $pdo->prepare('SELECT id, username, password_hash, role FROM users WHERE username = :u LIMIT 1');
    $stmt->execute(['u' => $username]);
    $user = $stmt->fetch();
    if ($user) {
        $hash = $user['password_hash'];
        $ok = false;
        if (password_verify($password, $hash)) {
            $ok = true;
        } else {
            // fallback to crypt comparison for hashes generated by Postgres crypt()
            if (strlen($hash) > 0 && crypt($password, $hash) === $hash) {
                $ok = true;
            }
        }

        if ($ok) {
            $_SESSION['user'] = [
                'id' => $user['id'],
                'username' => $user['username'],
                'role' => $user['role'],
            ];
            header('Location: dashboard.php');
            exit;
        }
    }
    $error = 'Usuario o contraseña inválidos';
}

?>
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Insertos - Iniciar sesión</title>
  <link rel="stylesheet" href="styles.css">
  <meta name="viewport" content="width=device-width,initial-scale=1">
</head>
<body>
  <div class="login-container">
    <div class="login-box">
      <div class="login-logo">
        <div class="login-logo-icon">⚙️</div>
        <h1 class="login-logo-text">VALMET</h1>
        <p class="login-logo-subtext">Sistema de Insertos</p>
      </div>

      <?php if ($error): ?>
        <div class="alert alert-danger">
          <span>⚠️</span>
          <span><?=htmlspecialchars($error)?></span>
        </div>
      <?php endif; ?>

      <form method="post" class="login-form">
        <div class="field">
          <label>Usuario</label>
          <input type="text" name="username" required placeholder="Ingrese su usuario">
        </div>

        <div class="field">
          <label>Contraseña</label>
          <input type="password" name="password" required placeholder="Ingrese su contraseña">
        </div>

        <button type="submit" style="width: 100%;">Iniciar sesión</button>
      </form>

      <div class="login-footer">
        <p class="text-muted">Usuarios de prueba: <strong>admin</strong> / <strong>user</strong></p>
      </div>
    </div>
  </div>
</body>
</html>
